# Generated by Django 2.2.1 on 2019-07-28 16:53

from django.db import migrations, models
import django.utils.timezone
import preview.models


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='add Item image', upload_to=preview.models.get_uplaod_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
