# Generated by Django 2.2.1 on 2019-07-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0002_contacthelp_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactHelp',
            new_name='Contact',
        ),
    ]
