# Generated by Django 2.2.1 on 2019-08-14 16:32

from django.db import migrations, models
import django.utils.timezone
import preview.models


class Migration(migrations.Migration):

    dependencies = [
        ('preview', '0003_auto_20190728_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='Add Image', upload_to=preview.models.get_uplaod_file_name)),
                ('document', models.FileField(default='Add Document', upload_to='documents')),
                ('video', models.FileField(default='Add Video File', upload_to=preview.models.get_uplaod_file_doc_name)),
            ],
        ),
    ]
